services:
  backend:
    build:
      context: .
      dockerfile: ./src/backend/Dockerfile
    volumes:
     - .:/microservice
    env_file:
      - .env
    depends_on:
      backend_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent --show-error http://localhost:8001/api/health || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  usersapi:
    build:
      context: .
      dockerfile: ./src/usersApi/Dockerfile
    volumes:
     - .:/microservice
    env_file:
      - .env
    depends_on:
      users_db:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent --show-error http://localhost:8000/api/users/health || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  auth_service:
    build:
      context: .
      dockerfile: ./src/authApi/Dockerfile
    expose:
      - "9000"
    env_file:
      - .env
    
# --- NGINX ---
  gateway:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - usersapi
      - backend
      - swagger_ui
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  # --- SWAGGER UI ---
  swagger_ui:
    image: swaggerapi/swagger-ui
    environment:
      URLS: >
        [
          { "url": "/api/users/openapi.json", "name": "Users Service" },
          { "url": "/openapi.json", "name": "Blog Service" }
        ]

  push-notificator:
      image: ghcr.io/ayusavin/push-notification-playground:1.0.0
      ports:
        - "8000:8000"
  worker: 
    build:
      context: .
      dockerfile: ./src/worker/Dockerfile
    volumes:
     - .:/microservice
    env_file:
      - .env
    depends_on: [rabbitmq, push-notificator, users_db]

  moderationworker: 
    build:
      context: .
      dockerfile: ./src/moderationWorker/Dockerfile
    volumes:
    - .:/microservice
    env_file:
      - .env
    depends_on:
      backend_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  previewworker: 
    build:
      context: .
      dockerfile: ./src/previewWorker/Dockerfile
    volumes:
    - .:/microservice
    env_file:
      - .env
    depends_on:
      backend_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  publishworker: 
    build:
      context: .
      dockerfile: ./src/publishWorker/Dockerfile
    volumes:
    - .:/microservice
    env_file:
      - .env
    depends_on:
      backend_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  backend_db:
    image: postgres:15
    container_name: backend_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend_db
    volumes:
      - backend_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 30s
      timeout: 10s
      retries: 5

  users_db:
    image: postgres:15
    container_name: users_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
    volumes:
      - users_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 30s
      timeout: 10s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
    backend_data:
    users_data:

networks:
  default:
    name: microservice_network
